-- MySQL Script generated by MySQL Workbench
-- Fri Jul 29 21:14:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hoy_se_juega
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hoy_se_juega` ;

-- -----------------------------------------------------
-- Schema hoy_se_juega
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hoy_se_juega` DEFAULT CHARACTER SET utf8 ;
USE `hoy_se_juega` ;

-- -----------------------------------------------------
-- Table `hoy_se_juega`.`auto_valoracion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`auto_valoracion` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`auto_valoracion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`canchas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`canchas` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`canchas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `identificacion` VARCHAR(45) NOT NULL,
  `capacidad` INT NOT NULL,
  `valor` INT NOT NULL,
  `users_owners_id` INT NOT NULL,
  `tipo_de_cancha_id` INT NOT NULL,
  `deportes_players_id` INT NOT NULL,
  `img_c` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`, `users_owners_id`, `tipo_de_cancha_id`, `deportes_players_id`),
  CONSTRAINT `fk_canchas_users_owners1`
    FOREIGN KEY (`users_owners_id`)
    REFERENCES `hoy_se_juega`.`users_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_canchas_tipo_de_cancha1`
    FOREIGN KEY (`tipo_de_cancha_id`)
    REFERENCES `hoy_se_juega`.`tipo_de_cancha` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_canchas_deportes_players1`
    FOREIGN KEY (`deportes_players_id`)
    REFERENCES `hoy_se_juega`.`deportes_players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_canchas_users_owners1_idx` ON `hoy_se_juega`.`canchas` (`users_owners_id` ASC);

CREATE INDEX `fk_canchas_tipo_de_cancha1_idx` ON `hoy_se_juega`.`canchas` (`tipo_de_cancha_id` ASC);

CREATE INDEX `fk_canchas_deportes_players1_idx` ON `hoy_se_juega`.`canchas` (`deportes_players_id` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`canchas_horarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`canchas_horarios` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`canchas_horarios` (
  `canchas_id` INT NOT NULL,
  `horas_owners_id` INT NOT NULL,
  `dias_owners_id` INT NOT NULL,
  PRIMARY KEY (`canchas_id`, `horas_owners_id`, `dias_owners_id`),
  CONSTRAINT `fk_canchas_has_horas_owners_canchas1`
    FOREIGN KEY (`canchas_id`)
    REFERENCES `hoy_se_juega`.`canchas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_canchas_has_horas_owners_horas_owners1`
    FOREIGN KEY (`horas_owners_id`)
    REFERENCES `hoy_se_juega`.`horas_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_canchas_has_horas_owners_dias_owners1`
    FOREIGN KEY (`dias_owners_id`)
    REFERENCES `hoy_se_juega`.`dias_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_canchas_has_horas_owners_horas_owners1_idx` ON `hoy_se_juega`.`canchas_horarios` (`horas_owners_id` ASC);

CREATE INDEX `fk_canchas_has_horas_owners_canchas1_idx` ON `hoy_se_juega`.`canchas_horarios` (`canchas_id` ASC);

CREATE INDEX `fk_canchas_has_horas_owners_dias_owners1_idx` ON `hoy_se_juega`.`canchas_horarios` (`dias_owners_id` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`categorias` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  `deportes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `deportes_id`),
  CONSTRAINT `fk_categorias_deportes1`
    FOREIGN KEY (`deportes_id`)
    REFERENCES `hoy_se_juega`.`deportes_players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_categorias_deportes1_idx` ON `hoy_se_juega`.`categorias` (`deportes_id` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`deportes_players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`deportes_players` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`deportes_players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `deporte` VARCHAR(45) NOT NULL,
  `active` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`detalle_lugar_owners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`detalle_lugar_owners` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`detalle_lugar_owners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iluminacion` VARCHAR(2) NOT NULL,
  `estacionamiento` VARCHAR(2) NOT NULL,
  `wifi` VARCHAR(2) NOT NULL,
  `vestuario` VARCHAR(2) NOT NULL,
  `ducha` VARCHAR(2) NOT NULL,
  `parrilla` VARCHAR(2) NOT NULL,
  `quincho` VARCHAR(2) NOT NULL,
  `quiosco` VARCHAR(2) NOT NULL,
  `users_owners_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_owners_id`),
  CONSTRAINT `fk_detalle_lugar_owners_users_owners1`
    FOREIGN KEY (`users_owners_id`)
    REFERENCES `hoy_se_juega`.`users_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_detalle_lugar_owners_users_owners1_idx` ON `hoy_se_juega`.`detalle_lugar_owners` (`users_owners_id` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`dias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`dias` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`dias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`dias_y_horas_canchas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`dias_y_horas_canchas` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`dias_y_horas_canchas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `canchas_id` INT NOT NULL,
  `horas_id` INT NOT NULL,
  `dias_id` INT NOT NULL,
  PRIMARY KEY (`id`, `canchas_id`, `horas_id`, `dias_id`),
  CONSTRAINT `fk_dias_y_horas_canchas_canchas1`
    FOREIGN KEY (`canchas_id`)
    REFERENCES `hoy_se_juega`.`canchas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dias_y_horas_canchas_horas1`
    FOREIGN KEY (`horas_id`)
    REFERENCES `hoy_se_juega`.`horas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dias_y_horas_canchas_dias1`
    FOREIGN KEY (`dias_id`)
    REFERENCES `hoy_se_juega`.`dias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_dias_y_horas_canchas_canchas1_idx` ON `hoy_se_juega`.`dias_y_horas_canchas` (`canchas_id` ASC);

CREATE INDEX `fk_dias_y_horas_canchas_horas1_idx` ON `hoy_se_juega`.`dias_y_horas_canchas` (`horas_id` ASC);

CREATE INDEX `fk_dias_y_horas_canchas_dias1_idx` ON `hoy_se_juega`.`dias_y_horas_canchas` (`dias_id` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`dias_y_horas_escuelitas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`dias_y_horas_escuelitas` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`dias_y_horas_escuelitas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `escuelitas_id` INT NOT NULL,
  `horas_id` INT NOT NULL,
  `dias_id` INT NOT NULL,
  PRIMARY KEY (`id`, `escuelitas_id`, `horas_id`, `dias_id`),
  CONSTRAINT `fk_dias_y_horas_escuelitas_escuelitas1`
    FOREIGN KEY (`escuelitas_id`)
    REFERENCES `hoy_se_juega`.`escuelitas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dias_y_horas_escuelitas_horas1`
    FOREIGN KEY (`horas_id`)
    REFERENCES `hoy_se_juega`.`horas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dias_y_horas_escuelitas_dias1`
    FOREIGN KEY (`dias_id`)
    REFERENCES `hoy_se_juega`.`dias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_dias_y_horas_escuelitas_escuelitas1_idx` ON `hoy_se_juega`.`dias_y_horas_escuelitas` (`escuelitas_id` ASC);

CREATE INDEX `fk_dias_y_horas_escuelitas_horas1_idx` ON `hoy_se_juega`.`dias_y_horas_escuelitas` (`horas_id` ASC);

CREATE INDEX `fk_dias_y_horas_escuelitas_dias1_idx` ON `hoy_se_juega`.`dias_y_horas_escuelitas` (`dias_id` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`dias_y_horas_player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`dias_y_horas_player` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`dias_y_horas_player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dias_players_id` INT NOT NULL,
  `horas_players_id` INT NOT NULL,
  `users_players_id` INT NOT NULL,
  PRIMARY KEY (`id`, `dias_players_id`, `horas_players_id`, `users_players_id`),
  CONSTRAINT `fk_dias_y_horas_player_dias_players1`
    FOREIGN KEY (`dias_players_id`)
    REFERENCES `hoy_se_juega`.`dias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dias_y_horas_player_horas_players1`
    FOREIGN KEY (`horas_players_id`)
    REFERENCES `hoy_se_juega`.`horas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dias_y_horas_player_users_players1`
    FOREIGN KEY (`users_players_id`)
    REFERENCES `hoy_se_juega`.`users_players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;

CREATE INDEX `fk_dias_y_horas_player_dias_players1_idx` ON `hoy_se_juega`.`dias_y_horas_player` (`dias_players_id` ASC);

CREATE INDEX `fk_dias_y_horas_player_horas_players1_idx` ON `hoy_se_juega`.`dias_y_horas_player` (`horas_players_id` ASC);

CREATE INDEX `fk_dias_y_horas_player_users_players1_idx` ON `hoy_se_juega`.`dias_y_horas_player` (`users_players_id` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`dias_y_horas_torneos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`dias_y_horas_torneos` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`dias_y_horas_torneos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `torneos_id` INT NOT NULL,
  `horas_id` INT NOT NULL,
  `dias_id` INT NOT NULL,
  PRIMARY KEY (`id`, `torneos_id`, `horas_id`, `dias_id`),
  CONSTRAINT `fk_dias_y_horas_toneos_torneos1`
    FOREIGN KEY (`torneos_id`)
    REFERENCES `hoy_se_juega`.`torneos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dias_y_horas_torneos_horas1`
    FOREIGN KEY (`horas_id`)
    REFERENCES `hoy_se_juega`.`horas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dias_y_horas_torneos_dias1`
    FOREIGN KEY (`dias_id`)
    REFERENCES `hoy_se_juega`.`dias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_dias_y_horas_toneos_torneos1_idx` ON `hoy_se_juega`.`dias_y_horas_torneos` (`torneos_id` ASC);

CREATE INDEX `fk_dias_y_horas_torneos_horas1_idx` ON `hoy_se_juega`.`dias_y_horas_torneos` (`horas_id` ASC);

CREATE INDEX `fk_dias_y_horas_torneos_dias1_idx` ON `hoy_se_juega`.`dias_y_horas_torneos` (`dias_id` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`escuelitas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`escuelitas` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`escuelitas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `genero_id` INT NOT NULL,
  `valor` INT NOT NULL,
  `canchas_id` INT NOT NULL,
  `users_owners_id` INT NOT NULL,
  `img_e` VARCHAR(200) NOT NULL,
  `deportes_players_id` INT NOT NULL,
  `categoria` INT(100) NOT NULL,
  `alumnos` INT(100) NOT NULL,
  PRIMARY KEY (`id`, `genero_id`, `canchas_id`, `users_owners_id`, `deportes_players_id`),
  CONSTRAINT `fk_escuelitas_genero1`
    FOREIGN KEY (`genero_id`)
    REFERENCES `hoy_se_juega`.`genero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escuelitas_canchas1`
    FOREIGN KEY (`canchas_id`)
    REFERENCES `hoy_se_juega`.`canchas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escuelitas_users_owners1`
    FOREIGN KEY (`users_owners_id`)
    REFERENCES `hoy_se_juega`.`users_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escuelitas_deportes_players1`
    FOREIGN KEY (`deportes_players_id`)
    REFERENCES `hoy_se_juega`.`deportes_players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_escuelitas_genero1_idx` ON `hoy_se_juega`.`escuelitas` (`genero_id` ASC);

CREATE INDEX `fk_escuelitas_canchas1_idx` ON `hoy_se_juega`.`escuelitas` (`canchas_id` ASC);

CREATE INDEX `fk_escuelitas_users_owners1_idx` ON `hoy_se_juega`.`escuelitas` (`users_owners_id` ASC);

CREATE INDEX `fk_escuelitas_deportes_players1_idx` ON `hoy_se_juega`.`escuelitas` (`deportes_players_id` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`escuelitas_horarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`escuelitas_horarios` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`escuelitas_horarios` (
  `escuelitas_id` INT NOT NULL,
  `horas_owners_id` INT NOT NULL,
  `dias_owners_id` INT NOT NULL,
  PRIMARY KEY (`escuelitas_id`, `horas_owners_id`, `dias_owners_id`),
  CONSTRAINT `fk_escuelitas_has_horas_owners_escuelitas1`
    FOREIGN KEY (`escuelitas_id`)
    REFERENCES `hoy_se_juega`.`escuelitas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escuelitas_has_horas_owners_horas_owners1`
    FOREIGN KEY (`horas_owners_id`)
    REFERENCES `hoy_se_juega`.`horas_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escuelitas_has_horas_owners_dias_owners1`
    FOREIGN KEY (`dias_owners_id`)
    REFERENCES `hoy_se_juega`.`dias_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_escuelitas_has_horas_owners_horas_owners1_idx` ON `hoy_se_juega`.`escuelitas_horarios` (`horas_owners_id` ASC);

CREATE INDEX `fk_escuelitas_has_horas_owners_escuelitas1_idx` ON `hoy_se_juega`.`escuelitas_horarios` (`escuelitas_id` ASC);

CREATE INDEX `fk_escuelitas_has_horas_owners_dias_owners1_idx` ON `hoy_se_juega`.`escuelitas_horarios` (`dias_owners_id` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`genero` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`genero` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`horas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`horas` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`horas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hora` TIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`imagen_escuelitas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`imagen_escuelitas` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`imagen_escuelitas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `link` VARCHAR(100) NOT NULL,
  `escuelitas_id` INT NOT NULL,
  PRIMARY KEY (`id`, `escuelitas_id`),
  CONSTRAINT `fk_imagen_escuelitas_escuelitas1`
    FOREIGN KEY (`escuelitas_id`)
    REFERENCES `hoy_se_juega`.`escuelitas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_imagen_escuelitas_escuelitas1_idx` ON `hoy_se_juega`.`imagen_escuelitas` (`escuelitas_id` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`imagenes_owners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`imagenes_owners` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`imagenes_owners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(100) NOT NULL,
  `image2` VARCHAR(100) NULL,
  `image3` VARCHAR(100) NULL,
  `users_owners_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_owners_id`),
  CONSTRAINT `fk_imagenes_owners_users_owners1`
    FOREIGN KEY (`users_owners_id`)
    REFERENCES `hoy_se_juega`.`users_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_imagenes_owners_users_owners1_idx` ON `hoy_se_juega`.`imagenes_owners` (`users_owners_id` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`imagenes_players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`imagenes_players` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`imagenes_players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `foto` VARCHAR(100) NOT NULL,
  `users_players_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_players_id`),
  CONSTRAINT `fk_imagenes_players_user_players1`
    FOREIGN KEY (`users_players_id`)
    REFERENCES `hoy_se_juega`.`users_players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_imagenes_players_user_players1_idx` ON `hoy_se_juega`.`imagenes_players` (`users_players_id` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`imagen_torneos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`imagen_torneos` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`imagen_torneos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `link` VARCHAR(100) NOT NULL,
  `torneos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `torneos_id`),
  CONSTRAINT `fk_imagen_escuelitas_copy1_torneos1`
    FOREIGN KEY (`torneos_id`)
    REFERENCES `hoy_se_juega`.`torneos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_imagen_escuelitas_copy1_torneos1_idx` ON `hoy_se_juega`.`imagen_torneos` (`torneos_id` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`logo_owners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`logo_owners` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`logo_owners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logo` VARCHAR(100) NOT NULL,
  `users_owners_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_owners_id`),
  CONSTRAINT `fk_logo_owners_users_owners1`
    FOREIGN KEY (`users_owners_id`)
    REFERENCES `hoy_se_juega`.`users_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_logo_owners_users_owners1_idx` ON `hoy_se_juega`.`logo_owners` (`users_owners_id` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`medios_de_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`medios_de_pago` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`medios_de_pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `transferencia` VARCHAR(2) NOT NULL,
  `mercado_pago` VARCHAR(2) NOT NULL,
  `efectivo` VARCHAR(2) NOT NULL,
  `tarjeta` VARCHAR(2) NOT NULL,
  `users_owners_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_owners_id`),
  CONSTRAINT `fk_medios_de_pago_users_owners1`
    FOREIGN KEY (`users_owners_id`)
    REFERENCES `hoy_se_juega`.`users_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_medios_de_pago_users_owners1_idx` ON `hoy_se_juega`.`medios_de_pago` (`users_owners_id` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`profesor` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`profesor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `users_owners_id` INT NOT NULL,
  `escuelitas_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_owners_id`, `escuelitas_id`),
  CONSTRAINT `fk_profesor_users_owners1`
    FOREIGN KEY (`users_owners_id`)
    REFERENCES `hoy_se_juega`.`users_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesor_escuelitas1`
    FOREIGN KEY (`escuelitas_id`)
    REFERENCES `hoy_se_juega`.`escuelitas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_profesor_users_owners1_idx` ON `hoy_se_juega`.`profesor` (`users_owners_id` ASC);

CREATE INDEX `fk_profesor_escuelitas1_idx` ON `hoy_se_juega`.`profesor` (`escuelitas_id` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`profesores_escuelitas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`profesores_escuelitas` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`profesores_escuelitas` (
  `escuelitas_id` INT NOT NULL,
  `escuelitas_deporte_id` INT NOT NULL,
  `escuelitas_genero_id` INT NOT NULL,
  `profesor_id` INT NOT NULL,
  `profesor_users_owners_id` INT NOT NULL,
  PRIMARY KEY (`escuelitas_id`, `escuelitas_deporte_id`, `escuelitas_genero_id`, `profesor_id`, `profesor_users_owners_id`),
  CONSTRAINT `fk_profesor_has_escuelitas_escuelitas1`
    FOREIGN KEY (`escuelitas_id` , `escuelitas_genero_id`)
    REFERENCES `hoy_se_juega`.`escuelitas` (`id` , `genero_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesores_escuelitas_profesor1`
    FOREIGN KEY (`profesor_id` , `profesor_users_owners_id`)
    REFERENCES `hoy_se_juega`.`profesor` (`id` , `users_owners_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_profesor_has_escuelitas_escuelitas1_idx` ON `hoy_se_juega`.`profesores_escuelitas` (`escuelitas_id` ASC, `escuelitas_deporte_id` ASC, `escuelitas_genero_id` ASC);

CREATE INDEX `fk_profesores_escuelitas_profesor1_idx` ON `hoy_se_juega`.`profesores_escuelitas` (`profesor_id` ASC, `profesor_users_owners_id` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`telefonos_owners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`telefonos_owners` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`telefonos_owners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(200) NOT NULL,
  `telefono2` VARCHAR(200) NOT NULL,
  `users_owners_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_owners_id`),
  CONSTRAINT `fk_telefonos_owners_users_owners1`
    FOREIGN KEY (`users_owners_id`)
    REFERENCES `hoy_se_juega`.`users_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_telefonos_owners_users_owners1_idx` ON `hoy_se_juega`.`telefonos_owners` (`users_owners_id` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`telefonos_players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`telefonos_players` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`telefonos_players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(200) NOT NULL,
  `telefono2` VARCHAR(200) NOT NULL,
  `users_players_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_players_id`),
  CONSTRAINT `fk_telefonos_players_users_players`
    FOREIGN KEY (`users_players_id`)
    REFERENCES `hoy_se_juega`.`users_players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_telefonos_players_users_players1_idx` ON `hoy_se_juega`.`telefonos_players` (`users_players_id` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`tipo_de_cancha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`tipo_de_cancha` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`tipo_de_cancha` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `material` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`torneos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`torneos` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`torneos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `deporte_id` INT NOT NULL,
  `genero_id` INT NOT NULL,
  `cantidad_equipos` INT NOT NULL,
  `categoria` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `valor` INT NOT NULL,
  `premio` INT NOT NULL,
  `users_owners_id` INT NOT NULL,
  PRIMARY KEY (`id`, `deporte_id`, `genero_id`, `users_owners_id`),
  CONSTRAINT `fk_torneos_deporte1`
    FOREIGN KEY (`deporte_id`)
    REFERENCES `hoy_se_juega`.`deporte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_torneos_genero1`
    FOREIGN KEY (`genero_id`)
    REFERENCES `hoy_se_juega`.`genero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_torneos_users_owners1`
    FOREIGN KEY (`users_owners_id`)
    REFERENCES `hoy_se_juega`.`users_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_torneos_deporte1_idx` ON `hoy_se_juega`.`torneos` (`deporte_id` ASC);

CREATE INDEX `fk_torneos_genero1_idx` ON `hoy_se_juega`.`torneos` (`genero_id` ASC);

CREATE INDEX `fk_torneos_users_owners1_idx` ON `hoy_se_juega`.`torneos` (`users_owners_id` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`ubicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`ubicacion` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`ubicacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `provincia` VARCHAR(100) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numeracion` INT NOT NULL,
  `users_owners_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_owners_id`),
  CONSTRAINT `fk_ubicacion_users_owners1`
    FOREIGN KEY (`users_owners_id`)
    REFERENCES `hoy_se_juega`.`users_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ubicacion_users_owners1_idx` ON `hoy_se_juega`.`ubicacion` (`users_owners_id` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`users_owners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`users_owners` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`users_owners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `nombre_del_lugar` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`users_players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`users_players` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`users_players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `zonas_de_juego_id` INT NOT NULL,
  `auto_valoracion_id` INT NOT NULL,
  `deportes_players_id` INT NOT NULL,
  `deportes_players_id2` INT NOT NULL,
  PRIMARY KEY (`id`, `zonas_de_juego_id`, `auto_valoracion_id`, `deportes_players_id`, `deportes_players_id2`),
  CONSTRAINT `fk_user_players_zonas_de_juego1`
    FOREIGN KEY (`zonas_de_juego_id`)
    REFERENCES `hoy_se_juega`.`zonas_de_juego` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_players_auto_valoracion1`
    FOREIGN KEY (`auto_valoracion_id`)
    REFERENCES `hoy_se_juega`.`auto_valoracion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_players_deportes_players1`
    FOREIGN KEY (`deportes_players_id`)
    REFERENCES `hoy_se_juega`.`deportes_players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_players_deportes_players2`
    FOREIGN KEY (`deportes_players_id2`)
    REFERENCES `hoy_se_juega`.`deportes_players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_user_players_zonas_de_juego1_idx` ON `hoy_se_juega`.`users_players` (`zonas_de_juego_id` ASC);

CREATE INDEX `fk_users_players_auto_valoracion1_idx` ON `hoy_se_juega`.`users_players` (`auto_valoracion_id` ASC);

CREATE INDEX `fk_users_players_deportes_players1_idx` ON `hoy_se_juega`.`users_players` (`deportes_players_id` ASC);

CREATE INDEX `fk_users_players_deportes_players2_idx` ON `hoy_se_juega`.`users_players` (`deportes_players_id2` ASC);


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`zonas_de_juego`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`zonas_de_juego` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`zonas_de_juego` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `provincia` VARCHAR(45) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `hoy_se_juega`.`auto_valoracion`
-- -----------------------------------------------------
START TRANSACTION;
USE `hoy_se_juega`;
INSERT INTO `hoy_se_juega`.`auto_valoracion` (`id`, `tipo`) VALUES (1, 'Estrella');
INSERT INTO `hoy_se_juega`.`auto_valoracion` (`id`, `tipo`) VALUES (2, 'Copadito');
INSERT INTO `hoy_se_juega`.`auto_valoracion` (`id`, `tipo`) VALUES (3, 'Juego');
INSERT INTO `hoy_se_juega`.`auto_valoracion` (`id`, `tipo`) VALUES (4, 'Me defiendo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `hoy_se_juega`.`deportes_players`
-- -----------------------------------------------------
START TRANSACTION;
USE `hoy_se_juega`;
INSERT INTO `hoy_se_juega`.`deportes_players` (`id`, `deporte`, `active`) VALUES (1, 'Futbol', 1);
INSERT INTO `hoy_se_juega`.`deportes_players` (`id`, `deporte`, `active`) VALUES (2, 'Voley', 1);
INSERT INTO `hoy_se_juega`.`deportes_players` (`id`, `deporte`, `active`) VALUES (3, 'Basquet', 1);
INSERT INTO `hoy_se_juega`.`deportes_players` (`id`, `deporte`, `active`) VALUES (4, 'Padel', 0);
INSERT INTO `hoy_se_juega`.`deportes_players` (`id`, `deporte`, `active`) VALUES (5, 'Tenis', 1);
INSERT INTO `hoy_se_juega`.`deportes_players` (`id`, `deporte`, `active`) VALUES (6, 'No juego', 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `hoy_se_juega`.`dias`
-- -----------------------------------------------------
START TRANSACTION;
USE `hoy_se_juega`;
INSERT INTO `hoy_se_juega`.`dias` (`id`, `dia`) VALUES (1, 'Lunes');
INSERT INTO `hoy_se_juega`.`dias` (`id`, `dia`) VALUES (2, 'Martes');
INSERT INTO `hoy_se_juega`.`dias` (`id`, `dia`) VALUES (3, 'Miércoles');
INSERT INTO `hoy_se_juega`.`dias` (`id`, `dia`) VALUES (4, 'Jueves');
INSERT INTO `hoy_se_juega`.`dias` (`id`, `dia`) VALUES (5, 'Viernes');
INSERT INTO `hoy_se_juega`.`dias` (`id`, `dia`) VALUES (6, 'Sábado');
INSERT INTO `hoy_se_juega`.`dias` (`id`, `dia`) VALUES (7, 'Domingo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `hoy_se_juega`.`genero`
-- -----------------------------------------------------
START TRANSACTION;
USE `hoy_se_juega`;
INSERT INTO `hoy_se_juega`.`genero` (`id`, `genero`) VALUES (1, 'Femenino');
INSERT INTO `hoy_se_juega`.`genero` (`id`, `genero`) VALUES (2, 'Masculino');
INSERT INTO `hoy_se_juega`.`genero` (`id`, `genero`) VALUES (3, 'Mixto');

COMMIT;


-- -----------------------------------------------------
-- Data for table `hoy_se_juega`.`horas`
-- -----------------------------------------------------
START TRANSACTION;
USE `hoy_se_juega`;
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (1, '00:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (2, '00:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (3, '01:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (4, '01:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (5, '02:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (6, '02:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (7, '03:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (8, '03:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (9, '04:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (10, '04:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (11, '05:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (12, '05:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (13, '06:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (14, '06:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (15, '07:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (16, '07:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (17, '08:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (18, '08:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (19, '09:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (20, '09:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (21, '10:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (22, '10:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (23, '11:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (24, '11:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (25, '12:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (26, '12:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (27, '13:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (28, '13:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (29, '14:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (30, '14:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (31, '15:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (32, '15:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (33, '16:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (34, '16:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (35, '17:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (36, '17:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (37, '18:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (38, '18:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (39, '19:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (40, '19:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (41, '20:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (42, '20:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (43, '21:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (44, '21:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (45, '22:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (46, '22:30');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (47, '23:00');
INSERT INTO `hoy_se_juega`.`horas` (`id`, `hora`) VALUES (48, '23:30');

COMMIT;


-- -----------------------------------------------------
-- Data for table `hoy_se_juega`.`tipo_de_cancha`
-- -----------------------------------------------------
START TRANSACTION;
USE `hoy_se_juega`;
INSERT INTO `hoy_se_juega`.`tipo_de_cancha` (`id`, `material`) VALUES (1, 'Césped');
INSERT INTO `hoy_se_juega`.`tipo_de_cancha` (`id`, `material`) VALUES (2, 'Césped sintético');
INSERT INTO `hoy_se_juega`.`tipo_de_cancha` (`id`, `material`) VALUES (3, 'Cemento');
INSERT INTO `hoy_se_juega`.`tipo_de_cancha` (`id`, `material`) VALUES (4, 'Ladrillo');
INSERT INTO `hoy_se_juega`.`tipo_de_cancha` (`id`, `material`) VALUES (5, 'Parqué');

COMMIT;


-- -----------------------------------------------------
-- Data for table `hoy_se_juega`.`zonas_de_juego`
-- -----------------------------------------------------
START TRANSACTION;
USE `hoy_se_juega`;
INSERT INTO `hoy_se_juega`.`zonas_de_juego` (`id`, `provincia`, `localidad`, `municipio`) VALUES (1, 'Buenos Aires', 'San fernando', 'Carupa');
INSERT INTO `hoy_se_juega`.`zonas_de_juego` (`id`, `provincia`, `localidad`, `municipio`) VALUES (2, 'Mendoza', 'Guaymallen', 'Dorrego');

COMMIT;

