-- MySQL Script generated by MySQL Workbench
-- Sun Aug  7 15:18:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hoy_se_juega
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hoy_se_juega` ;

-- -----------------------------------------------------
-- Schema hoy_se_juega
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hoy_se_juega` DEFAULT CHARACTER SET utf8 ;
USE `hoy_se_juega` ;

-- -----------------------------------------------------
-- Table `hoy_se_juega`.`auto_valoracion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`auto_valoracion` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`auto_valoracion` (
  `id` INT(11) NOT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`deportes_players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`deportes_players` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`deportes_players` (
  `id` INT(11) NOT NULL,
  `deporte` VARCHAR(45) NOT NULL,
  `active` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`tipo_de_cancha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`tipo_de_cancha` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`tipo_de_cancha` (
  `id` INT(11) NOT NULL,
  `material` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`users_owners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`users_owners` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`users_owners` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `nombre_del_lugar` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`canchas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`canchas` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`canchas` (
  `id` INT(11) NOT NULL,
  `identificacion` VARCHAR(45) NOT NULL,
  `capacidad` INT(11) NOT NULL,
  `valor` INT(11) NOT NULL,
  `users_owners_id` INT(11) NOT NULL,
  `tipo_de_cancha_id` INT(11) NOT NULL,
  `deportes_players_id` INT(11) NOT NULL,
  `img_c` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`, `users_owners_id`, `tipo_de_cancha_id`, `deportes_players_id`),
  INDEX `fk_canchas_users_owners1_idx` (`users_owners_id` ASC),
  INDEX `fk_canchas_tipo_de_cancha1_idx` (`tipo_de_cancha_id` ASC),
  INDEX `fk_canchas_deportes_players1_idx` (`deportes_players_id` ASC),
  CONSTRAINT `fk_canchas_deportes_players1`
    FOREIGN KEY (`deportes_players_id`)
    REFERENCES `hoy_se_juega`.`deportes_players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_canchas_tipo_de_cancha1`
    FOREIGN KEY (`tipo_de_cancha_id`)
    REFERENCES `hoy_se_juega`.`tipo_de_cancha` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_canchas_users_owners1`
    FOREIGN KEY (`users_owners_id`)
    REFERENCES `hoy_se_juega`.`users_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`categorias` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`categorias` (
  `id` INT(11) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `deportes_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `deportes_id`),
  INDEX `fk_categorias_deportes1_idx` (`deportes_id` ASC),
  CONSTRAINT `fk_categorias_deportes1`
    FOREIGN KEY (`deportes_id`)
    REFERENCES `hoy_se_juega`.`deportes_players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`detalle_lugar_owners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`detalle_lugar_owners` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`detalle_lugar_owners` (
  `id` INT(11) NOT NULL,
  `iluminacion` VARCHAR(2) NOT NULL,
  `estacionamiento` VARCHAR(2) NOT NULL,
  `wifi` VARCHAR(2) NOT NULL,
  `vestuario` VARCHAR(2) NOT NULL,
  `ducha` VARCHAR(2) NOT NULL,
  `parrilla` VARCHAR(2) NOT NULL,
  `quincho` VARCHAR(2) NOT NULL,
  `quiosco` VARCHAR(2) NOT NULL,
  `users_owners_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `users_owners_id`),
  INDEX `fk_detalle_lugar_owners_users_owners1_idx` (`users_owners_id` ASC),
  CONSTRAINT `fk_detalle_lugar_owners_users_owners1`
    FOREIGN KEY (`users_owners_id`)
    REFERENCES `hoy_se_juega`.`users_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`dias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`dias` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`dias` (
  `id` INT(11) NOT NULL,
  `dia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`horas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`horas` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`horas` (
  `id` INT(11) NOT NULL,
  `hora` TIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`dias_y_horas_canchas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`dias_y_horas_canchas` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`dias_y_horas_canchas` (
  `id` INT(11) NOT NULL,
  `canchas_id` INT(11) NOT NULL,
  `horas_id` INT(11) NOT NULL,
  `dias_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `canchas_id`, `horas_id`, `dias_id`),
  INDEX `fk_dias_y_horas_canchas_canchas1_idx` (`canchas_id` ASC),
  INDEX `fk_dias_y_horas_canchas_horas1_idx` (`horas_id` ASC),
  INDEX `fk_dias_y_horas_canchas_dias1_idx` (`dias_id` ASC),
  CONSTRAINT `fk_dias_y_horas_canchas_canchas1`
    FOREIGN KEY (`canchas_id`)
    REFERENCES `hoy_se_juega`.`canchas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dias_y_horas_canchas_dias1`
    FOREIGN KEY (`dias_id`)
    REFERENCES `hoy_se_juega`.`dias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dias_y_horas_canchas_horas1`
    FOREIGN KEY (`horas_id`)
    REFERENCES `hoy_se_juega`.`horas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`genero` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`genero` (
  `id` INT(11) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`escuelitas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`escuelitas` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`escuelitas` (
  `id` INT(11) NOT NULL,
  `genero_id` INT(11) NOT NULL,
  `valor` INT(11) NOT NULL,
  `users_owners_id` INT(11) NOT NULL,
  `img_e` VARCHAR(200) NOT NULL,
  `deportes_players_id` INT(11) NOT NULL,
  `categoria` INT(100) NOT NULL,
  `alumnos` INT(100) NOT NULL,
  PRIMARY KEY (`id`, `genero_id`, `users_owners_id`, `deportes_players_id`),
  INDEX `fk_escuelitas_genero1_idx` (`genero_id` ASC),
  INDEX `fk_escuelitas_canchas1_idx` (),
  INDEX `fk_escuelitas_users_owners1_idx` (`users_owners_id` ASC),
  INDEX `fk_escuelitas_deportes_players1_idx` (`deportes_players_id` ASC),
  CONSTRAINT `fk_escuelitas_canchas1`
    FOREIGN KEY ()
    REFERENCES `hoy_se_juega`.`canchas` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escuelitas_deportes_players1`
    FOREIGN KEY (`deportes_players_id`)
    REFERENCES `hoy_se_juega`.`deportes_players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escuelitas_genero1`
    FOREIGN KEY (`genero_id`)
    REFERENCES `hoy_se_juega`.`genero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escuelitas_users_owners1`
    FOREIGN KEY (`users_owners_id`)
    REFERENCES `hoy_se_juega`.`users_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`dias_y_horas_escuelitas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`dias_y_horas_escuelitas` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`dias_y_horas_escuelitas` (
  `id` INT(11) NOT NULL,
  `escuelitas_id` INT(11) NOT NULL,
  `horas_id` INT(11) NOT NULL,
  `dias_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `escuelitas_id`, `horas_id`, `dias_id`),
  INDEX `fk_dias_y_horas_escuelitas_escuelitas1_idx` (`escuelitas_id` ASC),
  INDEX `fk_dias_y_horas_escuelitas_horas1_idx` (`horas_id` ASC),
  INDEX `fk_dias_y_horas_escuelitas_dias1_idx` (`dias_id` ASC),
  CONSTRAINT `fk_dias_y_horas_escuelitas_dias1`
    FOREIGN KEY (`dias_id`)
    REFERENCES `hoy_se_juega`.`dias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dias_y_horas_escuelitas_escuelitas1`
    FOREIGN KEY (`escuelitas_id`)
    REFERENCES `hoy_se_juega`.`escuelitas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dias_y_horas_escuelitas_horas1`
    FOREIGN KEY (`horas_id`)
    REFERENCES `hoy_se_juega`.`horas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`zonas_de_juego`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`zonas_de_juego` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`zonas_de_juego` (
  `id` INT(11) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`users_players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`users_players` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`users_players` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `zonas_de_juego_id` INT(11) NOT NULL,
  `auto_valoracion_id` INT(11) NOT NULL,
  `deportes_players_id` INT(11) NOT NULL,
  `deportes_players_id2` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `zonas_de_juego_id`, `auto_valoracion_id`, `deportes_players_id`, `deportes_players_id2`),
  INDEX `fk_user_players_zonas_de_juego1_idx` (`zonas_de_juego_id` ASC),
  INDEX `fk_users_players_auto_valoracion1_idx` (`auto_valoracion_id` ASC),
  INDEX `fk_users_players_deportes_players1_idx` (`deportes_players_id` ASC),
  INDEX `fk_users_players_deportes_players2_idx` (`deportes_players_id2` ASC),
  CONSTRAINT `fk_user_players_zonas_de_juego1`
    FOREIGN KEY (`zonas_de_juego_id`)
    REFERENCES `hoy_se_juega`.`zonas_de_juego` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_players_auto_valoracion1`
    FOREIGN KEY (`auto_valoracion_id`)
    REFERENCES `hoy_se_juega`.`auto_valoracion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_players_deportes_players1`
    FOREIGN KEY (`deportes_players_id`)
    REFERENCES `hoy_se_juega`.`deportes_players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_players_deportes_players2`
    FOREIGN KEY (`deportes_players_id2`)
    REFERENCES `hoy_se_juega`.`deportes_players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`dias_y_horas_player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`dias_y_horas_player` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`dias_y_horas_player` (
  `id` INT(11) NOT NULL,
  `dias_players_id` INT(11) NOT NULL,
  `horas_players_id` INT(11) NOT NULL,
  `users_players_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `dias_players_id`, `horas_players_id`, `users_players_id`),
  INDEX `fk_dias_y_horas_player_dias_players1_idx` (`dias_players_id` ASC),
  INDEX `fk_dias_y_horas_player_horas_players1_idx` (`horas_players_id` ASC),
  INDEX `fk_dias_y_horas_player_users_players1_idx` (`users_players_id` ASC),
  CONSTRAINT `fk_dias_y_horas_player_dias_players1`
    FOREIGN KEY (`dias_players_id`)
    REFERENCES `hoy_se_juega`.`dias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dias_y_horas_player_horas_players1`
    FOREIGN KEY (`horas_players_id`)
    REFERENCES `hoy_se_juega`.`horas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dias_y_horas_player_users_players1`
    FOREIGN KEY (`users_players_id`)
    REFERENCES `hoy_se_juega`.`users_players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`torneos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`torneos` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`torneos` (
  `id` INT(11) NOT NULL,
  `genero_id` INT(11) NOT NULL,
  `cantidad_equipos` INT(11) NOT NULL,
  `categoria` INT(11) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `valor` INT(11) NOT NULL,
  `premio` INT(11) NOT NULL,
  `users_owners_id` INT(11) NOT NULL,
  `img_t` VARCHAR(200) NULL DEFAULT NULL,
  `deportes_players_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `genero_id`, `users_owners_id`, `deportes_players_id`),
  INDEX `fk_torneos_genero1_idx` (`genero_id` ASC),
  INDEX `fk_torneos_users_owners1_idx` (`users_owners_id` ASC),
  INDEX `fk_torneos_deportes_players1_idx` (`deportes_players_id` ASC),
  CONSTRAINT `fk_torneos_deportes_players1`
    FOREIGN KEY (`deportes_players_id`)
    REFERENCES `hoy_se_juega`.`deportes_players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_torneos_genero1`
    FOREIGN KEY (`genero_id`)
    REFERENCES `hoy_se_juega`.`genero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_torneos_users_owners1`
    FOREIGN KEY (`users_owners_id`)
    REFERENCES `hoy_se_juega`.`users_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`dias_y_horas_torneos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`dias_y_horas_torneos` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`dias_y_horas_torneos` (
  `id` INT(11) NOT NULL,
  `torneos_id` INT(11) NOT NULL,
  `horas_id` INT(11) NOT NULL,
  `dias_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `torneos_id`, `horas_id`, `dias_id`),
  INDEX `fk_dias_y_horas_toneos_torneos1_idx` (`torneos_id` ASC),
  INDEX `fk_dias_y_horas_torneos_horas1_idx` (`horas_id` ASC),
  INDEX `fk_dias_y_horas_torneos_dias1_idx` (`dias_id` ASC),
  CONSTRAINT `fk_dias_y_horas_toneos_torneos1`
    FOREIGN KEY (`torneos_id`)
    REFERENCES `hoy_se_juega`.`torneos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dias_y_horas_torneos_dias1`
    FOREIGN KEY (`dias_id`)
    REFERENCES `hoy_se_juega`.`dias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dias_y_horas_torneos_horas1`
    FOREIGN KEY (`horas_id`)
    REFERENCES `hoy_se_juega`.`horas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`home_owners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`home_owners` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`home_owners` (
  `id` INT(11) NOT NULL,
  `users_owners_id` INT(11) NOT NULL,
  `nombre_del_lugar` VARCHAR(100) NOT NULL,
  `img_ho` VARCHAR(100) NOT NULL,
  `img_hl` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`, `users_owners_id`),
  INDEX `fk_home_owners_users_owners1_idx` (`users_owners_id` ASC),
  CONSTRAINT `fk_home_owners_users_owners1`
    FOREIGN KEY (`users_owners_id`)
    REFERENCES `hoy_se_juega`.`users_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`home_players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`home_players` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`home_players` (
  `id` INT(11) NOT NULL,
  `users_players_id` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `img_hp` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`, `users_players_id`),
  INDEX `fk_home_players_users_players1_idx` (`users_players_id` ASC),
  CONSTRAINT `fk_home_players_users_players1`
    FOREIGN KEY (`users_players_id`)
    REFERENCES `hoy_se_juega`.`users_players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`imagenes_owners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`imagenes_owners` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`imagenes_owners` (
  `id` INT(11) NOT NULL,
  `image` VARCHAR(100) NOT NULL,
  `image2` VARCHAR(100) NULL DEFAULT NULL,
  `image3` VARCHAR(100) NULL DEFAULT NULL,
  `users_owners_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `users_owners_id`),
  INDEX `fk_imagenes_owners_users_owners1_idx` (`users_owners_id` ASC),
  CONSTRAINT `fk_imagenes_owners_users_owners1`
    FOREIGN KEY (`users_owners_id`)
    REFERENCES `hoy_se_juega`.`users_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`imagenes_players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`imagenes_players` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`imagenes_players` (
  `id` INT(11) NOT NULL,
  `foto` VARCHAR(100) NOT NULL,
  `users_players_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `users_players_id`),
  INDEX `fk_imagenes_players_user_players1_idx` (`users_players_id` ASC),
  CONSTRAINT `fk_imagenes_players_user_players1`
    FOREIGN KEY (`users_players_id`)
    REFERENCES `hoy_se_juega`.`users_players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`imagen_escuelitas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`imagen_escuelitas` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`imagen_escuelitas` (
  `id` INT(11) NOT NULL,
  `link` VARCHAR(100) NOT NULL,
  `escuelitas_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `escuelitas_id`),
  INDEX `fk_imagen_escuelitas_escuelitas1_idx` (`escuelitas_id` ASC),
  CONSTRAINT `fk_imagen_escuelitas_escuelitas1`
    FOREIGN KEY (`escuelitas_id`)
    REFERENCES `hoy_se_juega`.`escuelitas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`logo_owners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`logo_owners` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`logo_owners` (
  `id` INT(11) NOT NULL,
  `logo` VARCHAR(100) NOT NULL,
  `users_owners_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `users_owners_id`),
  INDEX `fk_logo_owners_users_owners1_idx` (`users_owners_id` ASC),
  CONSTRAINT `fk_logo_owners_users_owners1`
    FOREIGN KEY (`users_owners_id`)
    REFERENCES `hoy_se_juega`.`users_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`medios_de_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`medios_de_pago` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`medios_de_pago` (
  `id` INT(11) NOT NULL,
  `transferencia` VARCHAR(2) NOT NULL,
  `mercado_pago` VARCHAR(2) NOT NULL,
  `efectivo` VARCHAR(2) NOT NULL,
  `tarjeta` VARCHAR(2) NOT NULL,
  `users_owners_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `users_owners_id`),
  INDEX `fk_medios_de_pago_users_owners1_idx` (`users_owners_id` ASC),
  CONSTRAINT `fk_medios_de_pago_users_owners1`
    FOREIGN KEY (`users_owners_id`)
    REFERENCES `hoy_se_juega`.`users_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`profesor` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`profesor` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `users_owners_id` INT(11) NOT NULL,
  `escuelitas_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `users_owners_id`, `escuelitas_id`),
  INDEX `fk_profesor_users_owners1_idx` (`users_owners_id` ASC),
  INDEX `fk_profesor_escuelitas1_idx` (`escuelitas_id` ASC),
  CONSTRAINT `fk_profesor_escuelitas1`
    FOREIGN KEY (`escuelitas_id`)
    REFERENCES `hoy_se_juega`.`escuelitas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesor_users_owners1`
    FOREIGN KEY (`users_owners_id`)
    REFERENCES `hoy_se_juega`.`users_owners` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`profesores_escuelitas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`profesores_escuelitas` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`profesores_escuelitas` (
  `escuelitas_id` INT(11) NOT NULL,
  `escuelitas_deporte_id` INT(11) NOT NULL,
  `escuelitas_genero_id` INT(11) NOT NULL,
  `profesor_id` INT(11) NOT NULL,
  `profesor_users_owners_id` INT(11) NOT NULL,
  PRIMARY KEY (`escuelitas_id`, `escuelitas_deporte_id`, `escuelitas_genero_id`, `profesor_id`, `profesor_users_owners_id`),
  INDEX `fk_profesor_has_escuelitas_escuelitas1` (`escuelitas_id` ASC, `escuelitas_genero_id` ASC),
  INDEX `fk_profesor_has_escuelitas_escuelitas1_idx` (`escuelitas_id` ASC, `escuelitas_deporte_id` ASC, `escuelitas_genero_id` ASC),
  INDEX `fk_profesores_escuelitas_profesor1_idx` (`profesor_id` ASC, `profesor_users_owners_id` ASC),
  CONSTRAINT `fk_profesor_has_escuelitas_escuelitas1`
    FOREIGN KEY (`escuelitas_id` , `escuelitas_genero_id`)
    REFERENCES `hoy_se_juega`.`escuelitas` (`id` , `genero_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesores_escuelitas_profesor1`
    FOREIGN KEY (`profesor_id` , `profesor_users_owners_id`)
    REFERENCES `hoy_se_juega`.`profesor` (`id` , `users_owners_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`telefonos_owners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`telefonos_owners` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`telefonos_owners` (
  `id` INT(11) NOT NULL,
  `telefono` VARCHAR(200) NOT NULL,
  `telefono2` VARCHAR(200) NOT NULL,
  `users_owners_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `users_owners_id`),
  INDEX `fk_telefonos_owners_users_owners1_idx` (`users_owners_id` ASC),
  CONSTRAINT `fk_telefonos_owners_users_owners1`
    FOREIGN KEY (`users_owners_id`)
    REFERENCES `hoy_se_juega`.`users_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`telefonos_players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`telefonos_players` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`telefonos_players` (
  `id` INT(11) NOT NULL,
  `telefono` VARCHAR(200) NOT NULL,
  `telefono2` VARCHAR(200) NOT NULL,
  `users_players_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `users_players_id`),
  INDEX `fk_telefonos_players_users_players1_idx` (`users_players_id` ASC),
  CONSTRAINT `fk_telefonos_players_users_players`
    FOREIGN KEY (`users_players_id`)
    REFERENCES `hoy_se_juega`.`users_players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hoy_se_juega`.`ubicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoy_se_juega`.`ubicacion` ;

CREATE TABLE IF NOT EXISTS `hoy_se_juega`.`ubicacion` (
  `id` INT(11) NOT NULL,
  `provincia` VARCHAR(100) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numeracion` INT(11) NOT NULL,
  `users_owners_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `users_owners_id`),
  INDEX `fk_ubicacion_users_owners1_idx` (`users_owners_id` ASC),
  CONSTRAINT `fk_ubicacion_users_owners1`
    FOREIGN KEY (`users_owners_id`)
    REFERENCES `hoy_se_juega`.`users_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
